version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: kslm
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3301:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

# Không cần khai báo volumes ở mức global nữa.
